### ISSUE TITLE
Status of Project?

### ISSUE THREAD

**Issue by CameronBrooks11** [openscad/openscad-library-manager#45]
Hi, I was wondering the current status of this project and whether it's accepting/looking for help/contributions. I've been seeing this pop up for a couple years with GSOC and I'd love to see a working implementation...I was going to apply at one point but it didn't quite line up with school

**Comment by t-paul** [comment]
Yes, it was a suggested topic for a while but only taken up this year. Status is that the core is working as prototype but now needs to transition to actual use. Help would be very much appreciated.

There is a not yet fully tested client version as Snap package and as Linux binary. This may need some polishing for a release and a bit of testing.
I also have a not quite finished patch for OpenSCAD itself that is supposed to use the library manager information to pick up the path to libraries automatically so they can be easily used in OpenSCAD without extra setup.

If you would like to help moving things forward, the best way would be via discussion on the [#openscad](https://web.libera.chat/?channel=#openscad) IRC channel on libera.chat.

**Comment by CameronBrooks11** [comment]
Sounds good will do
